Source/Web/Quiz.Web/Controllers/QuizController.cs
namespace Quiz.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using AutoMapper.QueryableExtensions;

    using Quiz.Data.UnitOfWork;
    using Quiz.Web.ViewModels.Questions;

    public class QuizController : BaseController
    {

        public QuizController(IQuizData data)
            : base(data)
        {
        }

        public ActionResult MultiChoiceMode()
        {
            return PartialView("_MultiChoiceModePartial");
        }

        public ActionResult BinaryMode()
        {
            return PartialView("_BinaryModePartial");
        }

        public ActionResult QuizMode()
        {
            return PartialView("QuizMode");
        }

        public ActionResult NextQuestionBinary(int? Id)
        {
            int pageNumber = Id.GetValueOrDefault(1);

            var count = this.Data.Questions.All().Count();

            if (pageNumber > count)
            {
                return PartialView("_QuizFinishedPartial");
            }

            var data = this.GetData<BinaryModeQuestionViewModel>().OrderBy(x => x.Id).Skip(pageNumber - 1).Take(1).First();

            data.Author = this.Data.Authors.All().OrderBy(x => Guid.NewGuid()).Take(1).First();
            TempData["Current"] = pageNumber + 1;

            return PartialView("_NextQuestionBinaryPartial", data);
        }

        [HttpPost]
        public ActionResult CheckQuestionBinary(int AuthorId, int QuoteId, bool Answer)
        {
            ViewBag.Current = TempData["Current"];
            var quote = this.Data.Quotes.GetById(QuoteId);

            var model = new AnswerViewModel();
            model.AuthorName = quote.Author.Name;

            if ((quote.AuthorId == AuthorId) == Answer)
            {
                model.Message = "Correct! The right answer is:";
                return PartialView("_AnswerBinaryPartial", model);
            }

            model.Message = "Sorry, you are wrong! The right answer is:";
            return PartialView("_AnswerBinaryPartial", model);
        }


        public ActionResult NextQuestionMultiChoice(int? Id)
        {
            int pageNumber = Id.GetValueOrDefault(1);

            var count = this.Data.Questions.All().Count();

            if (pageNumber > count)
            {
                return PartialView("_QuizFinishedPartial");
            }

            var data = this.GetData<MultipleChoiceQuestionFromViewModel>().OrderBy(x => x.Id).Skip(pageNumber - 1).Take(1).First();

            TempData["Current"] = pageNumber + 1;

            return PartialView("_NextQuestionMultiChoicePartial", data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CheckQuestionMultiChoice(MultipleChoiceQuestionFromViewModel model)
        {
            var quote = this.Data.Quotes.GetById(model.QuoteId);

            ViewBag.Current = TempData["Current"];

            var answer = new AnswerViewModel();
            answer.AuthorName = quote.Author.Name;
            if (model.AnswerId == quote.AuthorId)
            {
                answer.Message = "Correct! The right answer is:";

                return PartialView("_AnswerMultiChoicePartial", answer);
            }

            answer.Message = "Sorry, you are wrong! The right answer is:";

            return PartialView("_AnswerMultiChoicePartial", answer);
        }


        private IQueryable<TViewModel> GetData<TViewModel>()
        {
            return this.Data.Questions.All().Project().To<TViewModel>();
        }

    }
}

Source/Web/Quiz.Web/Views/Quiz/QuizMode.cshtml
<div class="row text-center">
    <h2>Choose Mode</h2>
</div>

<hr />

<div class="row text-center">

    <div class="col-md-6">
        @Ajax.ActionLink("Binary Mode", "BinaryMode", "Quiz", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "master-update-target", InsertionMode = InsertionMode.Replace }, new { @class = "btn btn-lg btn-primary" })
    </div>
    <div class="col-md-6">
        @Ajax.ActionLink("Multi Choice Mode", "MultiChoiceMode", "Quiz", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "master-update-target", InsertionMode = InsertionMode.Replace }, new { @class = "btn btn-lg btn-primary" })
    </div>

</div>

Source/Web/Quiz.Web/Views/Quiz/_AnswerBinaryPartial.cshtml
@model Quiz.Web.ViewModels.Questions.AnswerViewModel


<div class="text-center">
    <h3>
        @Html.DisplayFor(m => m.Message)  <span class="label label-danger">@Html.DisplayFor(m => m.AuthorName)</span>
    </h3>

    <div id="next-button">
        @Ajax.ActionLink("Next", "NextQuestionBinary", new { Id = ViewBag.Current }, new AjaxOptions { HttpMethod = "Get", UpdateTargetId = "main-update", InsertionMode = InsertionMode.Replace }, new { @class = "btn btn-primary" })
    </div>
</div>

Source/Web/Quiz.Web/Views/Quiz/_AnswerMultiChoicePartial.cshtml
@model Quiz.Web.ViewModels.Questions.AnswerViewModel

<div class="text-center">
    <h3>
        @Html.DisplayFor(m => m.Message)  <span class="label label-danger">@Html.DisplayFor(m => m.AuthorName)</span>
    </h3>

    <div id="next-button">
        @Ajax.ActionLink("Next", "NextQuestionMultiChoice", new { Id = ViewBag.Current }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "main-update", InsertionMode = InsertionMode.Replace }, new { @class = "btn btn-primary" })
    </div>
</div>

Source/Web/Quiz.Web/Views/Quiz/_BinaryModePartial.cshtml
<div id="main-update">
    @Html.Action("NextQuestionBinary", "Quiz")
</div>

Source/Web/Quiz.Web/Views/Quiz/_MultiChoiceModePartial.cshtml
<div id="main-update">
    @Html.Action("NextQuestionMultiChoice", "Quiz")
</div>

Source/Web/Quiz.Web/Views/Quiz/_NextQuestionBinaryPartial.cshtml
@model Quiz.Web.ViewModels.Questions.BinaryModeQuestionViewModel

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-primary">
            <div class="panel-heading">Who Said It?</div>
            <div class="panel-body">
                <span> @Html.DisplayNameFor(m => m.QuoteContent) :</span>
                <i>"@Html.DisplayFor(m => m.QuoteContent)"</i>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="text-center">
                       <h3>@Html.DisplayFor(m => m.Author.Name) ?</h3>
                    </div>
                    <div id="update-target">

                        <div class="col-md-6">
                            @Ajax.ActionLink("YES", "CheckQuestionBinary", new { AuthorId = Model.Author.Id, QuoteId = Model.QuoteId, Answer = true }, new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "update-target", InsertionMode = InsertionMode.Replace }, new { @class = "btn btn-success" })
                        </div>

                        <div class="col-md-6">
                            @Ajax.ActionLink("NO", "CheckQuestionBinary", new { AuthorId = Model.Author.Id, QuoteId = Model.QuoteId, Answer = false }, new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "update-target", InsertionMode = InsertionMode.Replace }, new { @class = "btn btn-danger pull-right" })
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Source/Web/Quiz.Web/Views/Quiz/_NextQuestionMultiChoicePartial.cshtml
@model Quiz.Web.ViewModels.Questions.MultipleChoiceQuestionFromViewModel

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-primary">
            <div class="panel-heading">Who Said It?</div>
            <div class="panel-body">
                <span> @Html.DisplayNameFor(m => m.QuoteContent) :</span>
                <i>"@Html.DisplayFor(m => m.QuoteContent)"</i>
                
            </div>

            <div class="panel-footer">

                <div id="update-target">

                    @using (Ajax.BeginForm("CheckQuestionMultiChoice", "Quiz", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "update-target", InsertionMode = InsertionMode.Replace }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, string.Empty, new { @class = "text-danger" })
                            <div class="row container">
                                <div class="col-md-12">
                                    @Html.HiddenFor(m => m.QuoteId)
                                    <div class="radio">
                                        @foreach (var option in Model.Options)
                                        {
                                            <div class="form-group">
                                                <label for="@option.Author.Name">@option.Author.Name</label>
                                                @Html.RadioButtonFor(m => m.AnswerId, option.Author.Id, new { Id = option.Author.Name })
                                            </div>
                                        }

                                    </div>
                                </div>
                            </div>
                            <div class="row container">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        @Html.Submit(new { value = "Submit Answer", @class = "btn btn-success" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                </div>

            </div>

        </div>
    </div>
</div>



@*<div class="row">
    <div class="col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">Who Said It?</div>
            <div class="panel-body">
                @Html.DisplayFor(m => m.QuoteContent)
            </div>
        </div>
    </div>
</div>

<div id="update-target">

    @using (Ajax.BeginForm("CheckQuestionMultiChoice", "Quiz", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "update-target", InsertionMode = InsertionMode.Replace }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, string.Empty, new { @class = "text-danger" })
            <div class="row container">
                <div class="col-md-12">
                    @Html.HiddenFor(m => m.QuoteId)
                    <div class="radio">
                        @foreach (var option in Model.Options)
                        {
                            <div class="form-group">
                                <label for="@option.Author.Name">@option.Author.Name</label>
                                @Html.RadioButtonFor(m => m.AnswerId, option.Author.Id, new { Id = option.Author.Name })
                            </div>
                        }

                    </div>
                </div>
            </div>
            <div class="row container">
                <div class="col-md-12">
                    <div class="form-group">
                        @Html.Submit(new { value = "Submit Answer", @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    }

</div>*@

Source/Web/Quiz.Web/Views/Quiz/_QuizFinishedPartial.cshtml
<div class="row">
    <div class="col-md-12 text-center">
        <h1>THE END</h1>
    </div>
</div>